name: libtrainsim-data-munich-u6 # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.8.0-3' # just for humans, typically '1.2+git' or '1.3.2'
summary: The U6 from Munich for libtrainsim # 79 char long summary
description: |
  This snap contains one example track for the libtrainsim train simulator.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
    run-on: all
  
parts:
  data-munich:
    # See 'snapcraft plugins'
    plugin: dump
    source-type: git
    source: https://git.thm.de/bahn-simulator/simulator-data.git
    override-build: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
        apt-get update
        apt-get install git-lfs
        git lfs install
        git lfs pull
        mkdir -p $SNAPCRAFT_PART_INSTALL/data
        cp -r production_data $SNAPCRAFT_PART_INSTALL/data/production_data
    build-packages:
        - git
        - curl
        - bash
    stage:
        - data

slots:
  libtrainsim-data-slot:
    interface: content
    content: data
    read:
      - $SNAP/data
